# database_allenatori.py
# Indice tattico: 1 (Difensivista/Pragmatico) - 10 (Ultra-Offensivo/High-Pressing)

DB_ALLENATORI = {
    # --- SERIE A ---
    "atalanta": {"allenatore": "Maurizio Sarri", "indice_tattico": 8},
    "bologna": {"allenatore": "Domenico Tedesco", "indice_tattico": 6},
    "cagliari": {"allenatore": "Fabio Pisacane", "indice_tattico": 5},
    "como": {"allenatore": "Cesc Fàbregas", "indice_tattico": 8},
    "fiorentina": {"allenatore": "Fabio Grosso", "indice_tattico": 6},
    "frosinone": {"allenatore": "Massimiliano Alvini", "indice_tattico": 5},
    "genoa": {"allenatore": "Daniele De Rossi", "indice_tattico": 6},
    "inter": {"allenatore": "Cristian Chivu", "indice_tattico": 6},
    "juventus": {"allenatore": "Luciano Spalletti", "indice_tattico": 8},
    "lazio": {"allenatore": "Gennaro Gattuso", "indice_tattico": 6},
    "lecce": {"allenatore": "Eusebio Di Francesco", "indice_tattico": 6},
    "milan": {"allenatore": "Ruben Amorim", "indice_tattico": 8},
    "monza": {"allenatore": "Ivan Juric", "indice_tattico": 8},
    "napoli": {"allenatore": "Massimiliano Allegri", "indice_tattico": 4},
    "parma": {"allenatore": "Carlos Cuesta", "indice_tattico": 6},
    "roma": {"allenatore": "Gian Piero Gasperini", "indice_tattico": 10},
    "sassuolo": {"allenatore": "Alberto Aquilani", "indice_tattico": 7},
    "torino": {"allenatore": "Ignazio Abate", "indice_tattico": 6},
    "udinese": {"allenatore": "Kosta Runjaic", "indice_tattico": 6},
    "venezia": {"allenatore": "Giovanni Stroppa", "indice_tattico": 6},

    # --- SERIE B ---
    "arezzo": {"allenatore": "Cristian Bucchi", "indice_tattico": 5},
    "ascoli": {"allenatore": "Daniele Tomei", "indice_tattico": 5},
    "avellino": {"allenatore": "Alessandro Nesta", "indice_tattico": 5},
    "benevento": {"allenatore": "Antonio Floro Flores", "indice_tattico": 6},
    "carrarese": {"allenatore": "Antonio Cioffi", "indice_tattico": 5},
    "catanzaro": {"allenatore": "Giorgio Gorgone", "indice_tattico": 6},
    "cesena": {"allenatore": "Alessandro Diamanti", "indice_tattico": 6},
    "cremonese": {"allenatore": "Marco Giampaolo", "indice_tattico": 6},
    "empoli": {"allenatore": "Guido Pagliuca", "indice_tattico": 6},
    "entella": {"allenatore": "Simone Chiappella", "indice_tattico": 5},
    "juve stabia": {"allenatore": "Ignazio De Giorgio", "indice_tattico": 5},
    "mantova": {"allenatore": "Francesco Modesto", "indice_tattico": 7},
    "modena": {"allenatore": "Alberto Galloppa", "indice_tattico": 6},
    "padova": {"allenatore": "Antonio Calabro", "indice_tattico": 5},
    "palermo": {"allenatore": "Filippo Inzaghi", "indice_tattico": 5},
    "pisa": {"allenatore": "Paolo Bianco", "indice_tattico": 5},
    "sampdoria": {"allenatore": "Bernardo Corradi", "indice_tattico": 5},
    "sudtirol": {"allenatore": "Matteo Possanzini", "indice_tattico": 6},
    "verona": {"allenatore": "Marco Baroni", "indice_tattico": 5},
    "vicenza": {"allenatore": "Fabio Gallo", "indice_tattico": 5},

    # --- BUNDESLIGA ---
    "stoccarda": {"allenatore": "Sebastian Hoeneß", "indice_tattico": 9},
    "bayern monaco": {"allenatore": "Vincent Kompany", "indice_tattico": 9},
    "friburgo": {"allenatore": "Julian Schuster", "indice_tattico": 6},
    "hoffenheim": {"allenatore": "Christian Ilzer", "indice_tattico": 7},
    "amburgo": {"allenatore": "Merlin Polzin", "indice_tattico": 6},
    "borussia": {"allenatore": "Niko Kovac", "indice_tattico": 4},
    "schalke": {"allenatore": "Miron Muslic", "indice_tattico": 6},
    "elversberg": {"allenatore": "Vincent Wagner", "indice_tattico": 5},
    "paderborn": {"allenatore": "Ralf Kettemann", "indice_tattico": 6},
    "borussia monchengladbach": {"allenatore": "Eugen Polanski", "indice_tattico": 6},
    "magonza": {"allenatore": "Urs Fischer", "indice_tattico": 3},
    "werder brema": {"allenatore": "Daniel Thioune", "indice_tattico": 5},
    "fc augusta": {"allenatore": "Manuel Baum", "indice_tattico": 5},
    "colonia": {"allenatore": "René Wagner", "indice_tattico": 5},
    "lipsia": {"allenatore": "Martín Demichelis", "indice_tattico": 7},
    "union berlino": {"allenatore": "Mauro Lustrinelli", "indice_tattico": 4},
    "eintracht francoforte": {"allenatore": "Adi Hütter", "indice_tattico": 8},
    "bayer leverkusen": {"allenatore": "Carles Martínez", "indice_tattico": 8},

    # --- PREMIER LEAGUE ---
    "arsenal": {"allenatore": "Mikel Arteta", "indice_tattico": 8},
    "aston villa": {"allenatore": "Unai Emery", "indice_tattico": 9},
    "bournemouth": {"allenatore": "Andoni Iraola", "indice_tattico": 8},
    "brentford": {"allenatore": "Thomas Frank", "indice_tattico": 6},
    "brighton": {"allenatore": "Fabian Hürzeler", "indice_tattico": 8},
    "chelsea": {"allenatore": "Enzo Maresca", "indice_tattico": 7},
    "crystal palace": {"allenatore": "Oliver Glasner", "indice_tattico": 7},
    "everton": {"allenatore": "Sean Dyche", "indice_tattico": 2},
    "fulham": {"allenatore": "Marco Silva", "indice_tattico": 6},
    "ipswich town": {"allenatore": "Kieran McKenna", "indice_tattico": 7},
    "leicester city": {"allenatore": "Ruud van Nistelrooy", "indice_tattico": 5},
    "liverpool": {"allenatore": "Arne Slot", "indice_tattico": 8},
    "manchester city": {"allenatore": "Pep Guardiola", "indice_tattico": 10},
    "manchester united": {"allenatore": "Rúben Amorim", "indice_tattico": 8},
    "newcastle united": {"allenatore": "Eddie Howe", "indice_tattico": 7},
    "nottingham forest": {"allenatore": "Nuno Espírito Santo", "indice_tattico": 4},
    "southampton": {"allenatore": "Russell Martin", "indice_tattico": 7},
    "tottenham": {"allenatore": "Ange Postecoglou", "indice_tattico": 10},
    "west ham": {"allenatore": "Julen Lopetegui", "indice_tattico": 5},
    "wolverhampton": {"allenatore": "Gary O'Neil", "indice_tattico": 5},

    # --- LA LIGA ---
    "real madrid": {"allenatore": "Carlo Ancelotti", "indice_tattico": 6},
    "barcellona": {"allenatore": "Hansi Flick", "indice_tattico": 10},
    "atletico madrid": {"allenatore": "Diego Simeone", "indice_tattico": 4},
    "athletic bilbao": {"allenatore": "Ernesto Valverde", "indice_tattico": 7},
    "girona": {"allenatore": "Míchel", "indice_tattico": 9},
    "real sociedad": {"allenatore": "Imanol Alguacil", "indice_tattico": 7},
    "real betis": {"allenatore": "Manuel Pellegrini", "indice_tattico": 6},
    "villarreal": {"allenatore": "Marcelino", "indice_tattico": 6},
    "valencia": {"allenatore": "Rubén Baraja", "indice_tattico": 4},
    "sevilla": {"allenatore": "García Pimienta", "indice_tattico": 8},
    "celta vigo": {"allenatore": "Claudio Giráldez", "indice_tattico": 6},
    "osasuna": {"allenatore": "Vicente Moreno", "indice_tattico": 4},
    "mallorca": {"allenatore": "Jagoba Arrasate", "indice_tattico": 5},
    "rayo vallecano": {"allenatore": "Íñigo Pérez", "indice_tattico": 6},
    "getafe": {"allenatore": "José Bordalás", "indice_tattico": 2},
    "alaves": {"allenatore": "Luis García Plaza", "indice_tattico": 5},
    "las palmas": {"allenatore": "Dinko Jeličić", "indice_tattico": 5},
    "almeria": {"allenatore": "Xavi García Pimienta", "indice_tattico": 7},
    "granada": {"allenatore": "Pacheta", "indice_tattico": 6},
    "cadice": {"allenatore": "Imanol Idiakez", "indice_tattico": 5},

    # --- LIGUE 1 ---
    "paris saint-germain": {"allenatore": "Luis Enrique", "indice_tattico": 9},
    "marseille": {"allenatore": "Roberto De Zerbi", "indice_tattico": 9},
    "monaco": {"allenatore": "Adi Hütter", "indice_tattico": 8},
    "lille": {"allenatore": "Bruno Génésio", "indice_tattico": 6},
    "lyon": {"allenatore": "Pierre Sage", "indice_tattico": 7},
    "nice": {"allenatore": "Franck Haise", "indice_tattico": 6},
    "brest": {"allenatore": "Eric Roy", "indice_tattico": 4},
    "lens": {"allenatore": "Will Still", "indice_tattico": 6},
    "strasbourg": {"allenatore": "Liam Rosenior", "indice_tattico": 6},
    "toulouse": {"allenatore": "Carles Martínez Novell", "indice_tattico": 5},
    "rennes": {"allenatore": "Julien Stéphan", "indice_tattico": 6},
    "reims": {"allenatore": "Luka Elsner", "indice_tattico": 5},
    "nantes": {"allenatore": "Antoine Kombouaré", "indice_tattico": 4},
    "montpellier": {"allenatore": "Jean-Louis Gasset", "indice_tattico": 5},
    "saint-etienne": {"allenatore": "Olivier Dall'Oglio", "indice_tattico": 5},
    "le havre": {"allenatore": "Didier Digard", "indice_tattico": 4},
    "angers": {"allenatore": "Alexandre Dujeux", "indice_tattico": 4},
    "auxerre": {"allenatore": "Christophe Pélissier", "indice_tattico": 5}
}