DB_STADI = {
   # SERIE A[cite: 1]
    "atalanta": {"stadio": "Gewiss Stadium", "citta": "Bergamo", "campo": "erba_naturale", "lat": 45.71, "lon": 9.68, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "bologna": {"stadio": "Stadio Renato Dall'Ara", "citta": "Bologna", "campo": "erba_naturale", "lat": 44.49, "lon": 11.31, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "cagliari": {"stadio": "Unipol Domus", "citta": "Cagliari", "campo": "erba_naturale", "lat": 39.20, "lon": 9.13, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "como": {"stadio": "Stadio Giuseppe Sinigaglia", "citta": "Como", "campo": "erba_naturale", "lat": 45.81, "lon": 9.07, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "empoli": {"stadio": "Stadio Carlo Castellani", "citta": "Empoli", "campo": "erba_naturale", "lat": 43.72, "lon": 10.95, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "fiorentina": {"stadio": "Stadio Artemio Franchi", "citta": "Firenze", "campo": "erba_naturale", "lat": 43.78, "lon": 11.28, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "genoa": {"stadio": "Stadio Luigi Ferraris", "citta": "Genova", "campo": "erba_naturale", "lat": 44.42, "lon": 8.95, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "hellas verona": {"stadio": "Stadio Marcantonio Bentegodi", "citta": "Verona", "campo": "erba_naturale", "lat": 45.43, "lon": 10.97, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "inter": {"stadio": "Stadio Giuseppe Meazza", "citta": "Milano", "campo": "erba_ibrida", "lat": 45.47, "lon": 9.12, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "juventus": {"stadio": "Allianz Stadium", "citta": "Torino", "campo": "erba_naturale", "lat": 45.10, "lon": 7.64, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "lazio": {"stadio": "Stadio Olimpico", "citta": "Roma", "campo": "erba_naturale", "lat": 41.93, "lon": 12.45, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "lecce": {"stadio": "Stadio Via del Mare", "citta": "Lecce", "campo": "erba_naturale", "lat": 40.36, "lon": 18.18, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "milan": {"stadio": "Stadio Giuseppe Meazza", "citta": "Milano", "campo": "erba_ibrida", "lat": 45.47, "lon": 9.12, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "monza": {"stadio": "U-Power Stadium", "citta": "Monza", "campo": "erba_naturale", "lat": 45.58, "lon": 9.27, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "napoli": {"stadio": "Stadio Diego Armando Maradona", "citta": "Napoli", "campo": "erba_naturale", "lat": 40.82, "lon": 14.19, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "parma": {"stadio": "Stadio Ennio Tardini", "citta": "Parma", "campo": "erba_naturale", "lat": 44.79, "lon": 10.33, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "roma": {"stadio": "Stadio Olimpico", "citta": "Roma", "campo": "erba_naturale", "lat": 41.93, "lon": 12.45, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "torino": {"stadio": "Stadio Olimpico Grande Torino", "citta": "Torino", "campo": "erba_naturale", "lat": 45.03, "lon": 7.65, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "udinese": {"stadio": "Bluenergy Stadium", "citta": "Udine", "campo": "erba_naturale", "lat": 46.06, "lon": 13.19, "media_cartellini": 2.6, "coperto": True}, #[cite: 1]
    "venezia": {"stadio": "Stadio Pier Luigi Penzo", "citta": "Venezia", "campo": "erba_naturale", "lat": 45.42, "lon": 12.36, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "frosinone": {"stadio": "Stadio Benito Stirpe", "citta": "Frosinone", "campo": "erba_naturale", "lat": 41.63, "lon": 13.34, "media_cartellini": 2.6, "coperto": False},    #[cite: 1]
    
    # BUNDESLIGA[cite: 1]
    "bayern munich": {"stadio": "Allianz Arena", "citta": "Munich", "campo": "erba_naturale", "lat": 48.21, "lon": 11.62, "media_cartellini": 1.8, "coperto": False}, #[cite: 1]
    "borussia dortmund": {"stadio": "Signal Iduna Park", "citta": "Dortmund", "campo": "erba_naturale", "lat": 51.49, "lon": 7.45, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "bayer leverkusen": {"stadio": "BayArena", "citta": "Leverkusen", "campo": "erba_naturale", "lat": 51.03, "lon": 7.00, "media_cartellini": 1.9, "coperto": False}, #[cite: 1]
    "rb leipzig": {"stadio": "Red Bull Arena", "citta": "Leipzig", "campo": "erba_naturale", "lat": 51.34, "lon": 12.34, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "eintracht frankfurt": {"stadio": "Deutsche Bank Park", "citta": "Frankfurt", "campo": "erba_naturale", "lat": 50.06, "lon": 8.64, "media_cartellini": 2.3, "coperto": True}, #[cite: 1]
    "vfl wolfsburg": {"stadio": "Volkswagen Arena", "citta": "Wolfsburg", "campo": "erba_naturale", "lat": 52.43, "lon": 10.80, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "borussia mgladbach": {"stadio": "Borussia-Park", "citta": "Monchengladbach", "campo": "erba_naturale", "lat": 51.16, "lon": 6.38, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "sc freiburg": {"stadio": "Europa-Park Stadion", "citta": "Freiburg", "campo": "erba_naturale", "lat": 48.01, "lon": 7.82, "media_cartellini": 1.9, "coperto": False}, #[cite: 1]
    "tsg hoffenheim": {"stadio": "PreZero Arena", "citta": "Sinsheim", "campo": "erba_naturale", "lat": 49.23, "lon": 8.87, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "vfb stuttgart": {"stadio": "MHPArena", "citta": "Stuttgart", "campo": "erba_naturale", "lat": 48.79, "lon": 9.23, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "werder bremen": {"stadio": "Wohninvest Weserstadion", "citta": "Bremen", "campo": "erba_naturale", "lat": 53.06, "lon": 8.83, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "fc augsburg": {"stadio": "WWK Arena", "citta": "Augsburg", "campo": "erba_naturale", "lat": 48.32, "lon": 10.88, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "mainz 05": {"stadio": "Mewa Arena", "citta": "Mainz", "campo": "erba_naturale", "lat": 49.98, "lon": 8.22, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "1. fc union berlin": {"stadio": "Stadion An der Alten Forsterei", "citta": "Berlin", "campo": "erba_naturale", "lat": 52.45, "lon": 13.56, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "fc st. pauli": {"stadio": "Millerntor-Stadion", "citta": "Hamburg", "campo": "erba_naturale", "lat": 53.55, "lon": 9.96, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "holstein kiel": {"stadio": "Holstein-Stadion", "citta": "Kiel", "campo": "erba_naturale", "lat": 54.34, "lon": 10.12, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "vfl bochum": {"stadio": "Vonovia Ruhrstadion", "citta": "Bochum", "campo": "erba_naturale", "lat": 51.48, "lon": 7.23, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "fc heidenheim": {"stadio": "Voith-Arena", "citta": "Heidenheim", "campo": "erba_naturale", "lat": 48.67, "lon": 10.16, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]

    # LA LIGA[cite: 1]
    "real madrid": {"stadio": "Santiago Bernabeu", "citta": "Madrid", "campo": "erba_ibrida", "lat": 40.45, "lon": -3.68, "media_cartellini": 1.9, "coperto": True}, #[cite: 1]
    "fc barcelona": {"stadio": "Estadi Olimpic Lluis Companys", "citta": "Barcelona", "campo": "erba_naturale", "lat": 41.36, "lon": 2.15, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "atletico madrid": {"stadio": "Metropolitano", "citta": "Madrid", "campo": "erba_naturale", "lat": 40.43, "lon": -3.59, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "athletic club": {"stadio": "San Mames", "citta": "Bilbao", "campo": "erba_naturale", "lat": 43.26, "lon": -2.94, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "villarreal": {"stadio": "Estadio de la Ceramica", "citta": "Villarreal", "campo": "erba_naturale", "lat": 39.94, "lon": -0.10, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "real sociedad": {"stadio": "Reale Arena", "citta": "San Sebastian", "campo": "erba_naturale", "lat": 43.30, "lon": -1.97, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "real betis": {"stadio": "Benito Villamarin", "citta": "Seville", "campo": "erba_naturale", "lat": 37.35, "lon": -5.98, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "sevilla": {"stadio": "Ramon Sanchez-Pizjuan", "citta": "Seville", "campo": "erba_naturale", "lat": 37.38, "lon": -5.97, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "girona": {"stadio": "Montilivi", "citta": "Girona", "campo": "erba_naturale", "lat": 41.96, "lon": 2.82, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "valencia": {"stadio": "Mestalla", "citta": "Valencia", "campo": "erba_naturale", "lat": 39.47, "lon": -0.35, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "osasuna": {"stadio": "El Sadar", "citta": "Pamplona", "campo": "erba_naturale", "lat": 42.79, "lon": -1.63, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "celta vigo": {"stadio": "Abanca-Balaidos", "citta": "Vigo", "campo": "erba_naturale", "lat": 42.21, "lon": -8.74, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "getafe": {"stadio": "Coliseum", "citta": "Getafe", "campo": "erba_naturale", "lat": 40.32, "lon": -3.72, "media_cartellini": 3.0, "coperto": False}, #[cite: 1]
    "mallorca": {"stadio": "Son Moix", "citta": "Palma", "campo": "erba_naturale", "lat": 39.59, "lon": 2.62, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "alaves": {"stadio": "Mendizorrotza", "citta": "Vitoria-Gasteiz", "campo": "erba_naturale", "lat": 42.84, "lon": -2.68, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "rayo vallecano": {"stadio": "Campo de Vallecas", "citta": "Madrid", "campo": "erba_naturale", "lat": 40.39, "lon": -3.65, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "las palmas": {"stadio": "Gran Canaria", "citta": "Las Palmas", "campo": "erba_naturale", "lat": 28.10, "lon": -15.45, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "espanyol": {"stadio": "Stage Front Stadium", "citta": "Barcelona", "campo": "erba_naturale", "lat": 41.34, "lon": 2.07, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "real valladolid": {"stadio": "Jose Zorrilla", "citta": "Valladolid", "campo": "erba_naturale", "lat": 41.65, "lon": -4.75, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "leganes": {"stadio": "Butarque", "citta": "Leganes", "campo": "erba_naturale", "lat": 40.33, "lon": -3.76, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]

    # LIGUE 1[cite: 1]
    "paris saint-germain": {"stadio": "Parc des Princes", "citta": "Paris", "campo": "erba_ibrida", "lat": 48.84, "lon": 2.25, "media_cartellini": 1.7, "coperto": False}, #[cite: 1]
    "olympique lyonnais": {"stadio": "Groupama Stadium", "citta": "Lyon", "campo": "erba_ibrida", "lat": 45.76, "lon": 4.97, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "olympique marseille": {"stadio": "Stade Velodrome", "citta": "Marseille", "campo": "erba_naturale", "lat": 43.26, "lon": 5.39, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "as monaco": {"stadio": "Stade Louis II", "citta": "Monaco", "campo": "erba_naturale", "lat": 43.72, "lon": 7.41, "media_cartellini": 1.9, "coperto": False}, #[cite: 1]
    "lille": {"stadio": "Stade Pierre-Mauroy", "citta": "Lille", "campo": "erba_ibrida", "lat": 50.61, "lon": 3.13, "media_cartellini": 2.2, "coperto": True}, #[cite: 1]
    "nice": {"stadio": "Allianz Riviera", "citta": "Nice", "campo": "erba_ibrida", "lat": 43.71, "lon": 7.18, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "lens": {"stadio": "Stade Bollaert-Delelis", "citta": "Lens", "campo": "erba_naturale", "lat": 50.43, "lon": 2.82, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "rennes": {"stadio": "Roazhon Park", "citta": "Rennes", "campo": "erba_naturale", "lat": 48.10, "lon": -1.71, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "stade de reims": {"stadio": "Stade Auguste-Delaune", "citta": "Reims", "campo": "erba_naturale", "lat": 49.24, "lon": 4.02, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "strasbourg": {"stadio": "Stade de la Meinau", "citta": "Strasbourg", "campo": "erba_naturale", "lat": 48.56, "lon": 7.75, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "toulouse": {"stadio": "Stadium de Toulouse", "citta": "Toulouse", "campo": "erba_naturale", "lat": 43.58, "lon": 1.43, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "nantes": {"stadio": "Stade de la Beaujoire", "citta": "Nantes", "campo": "erba_naturale", "lat": 47.25, "lon": -1.52, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "montpellier": {"stadio": "Stade de la Mosson", "citta": "Montpellier", "campo": "erba_naturale", "lat": 43.62, "lon": 3.81, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "le havre": {"stadio": "Stade Oceane", "citta": "Le Havre", "campo": "erba_naturale", "lat": 49.50, "lon": 0.17, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "auxerre": {"stadio": "Stade de l'Abbe-Deschamps", "citta": "Auxerre", "campo": "erba_naturale", "lat": 47.77, "lon": 3.58, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "saint-etienne": {"stadio": "Stade Geoffroy-Guichard", "citta": "Saint-Etienne", "campo": "erba_naturale", "lat": 45.45, "lon": 4.39, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "angers": {"stadio": "Stade Raymond Kopa", "citta": "Angers", "campo": "erba_naturale", "lat": 47.47, "lon": -0.55, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "brest": {"stadio": "Stade Francis-Le Ble", "citta": "Brest", "campo": "erba_naturale", "lat": 48.40, "lon": -4.49, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]

    # PREMIER LEAGUE[cite: 1]
    "arsenal": {"stadio": "Emirates Stadium", "citta": "London", "campo": "erba_naturale", "lat": 51.55, "lon": -0.10, "media_cartellini": 1.9, "coperto": False}, #[cite: 1]
    "aston villa": {"stadio": "Villa Park", "citta": "Birmingham", "campo": "erba_naturale", "lat": 52.50, "lon": -1.88, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "bournemouth": {"stadio": "Vitality Stadium", "citta": "Bournemouth", "campo": "erba_naturale", "lat": 50.73, "lon": -1.83, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "brentford": {"stadio": "Gtech Community Stadium", "citta": "London", "campo": "erba_naturale", "lat": 51.48, "lon": -0.28, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "brighton": {"stadio": "Amex Stadium", "citta": "Brighton", "campo": "erba_naturale", "lat": 50.86, "lon": -0.08, "media_cartellini": 2.0, "coperto": False}, #[cite: 1]
    "chelsea": {"stadio": "Stamford Bridge", "citta": "London", "campo": "erba_naturale", "lat": 51.48, "lon": -0.19, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "crystal palace": {"stadio": "Selhurst Park", "citta": "London", "campo": "erba_naturale", "lat": 51.39, "lon": -0.08, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "everton": {"stadio": "Goodison Park", "citta": "Liverpool", "campo": "erba_naturale", "lat": 53.44, "lon": -2.96, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "fulham": {"stadio": "Craven Cottage", "citta": "London", "campo": "erba_naturale", "lat": 51.47, "lon": -0.22, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "ipswich town": {"stadio": "Portman Road", "citta": "Ipswich", "campo": "erba_naturale", "lat": 52.05, "lon": 1.14, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "leicester city": {"stadio": "King Power Stadium", "citta": "Leicester", "campo": "erba_naturale", "lat": 52.62, "lon": -1.14, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "liverpool": {"stadio": "Anfield", "citta": "Liverpool", "campo": "erba_naturale", "lat": 53.43, "lon": -2.96, "media_cartellini": 1.8, "coperto": False}, #[cite: 1]
    "manchester city": {"stadio": "Etihad Stadium", "citta": "Manchester", "campo": "erba_ibrida", "lat": 53.48, "lon": -2.20, "media_cartellini": 1.7, "coperto": False}, #[cite: 1]
    "manchester united": {"stadio": "Old Trafford", "citta": "Manchester", "campo": "erba_naturale", "lat": 53.46, "lon": -2.29, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "newcastle united": {"stadio": "St. James' Park", "citta": "Newcastle", "campo": "erba_naturale", "lat": 54.97, "lon": -1.62, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "nottingham forest": {"stadio": "City Ground", "citta": "Nottingham", "campo": "erba_naturale", "lat": 52.93, "lon": -1.13, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "southampton": {"stadio": "St Mary's Stadium", "citta": "Southampton", "campo": "erba_naturale", "lat": 50.90, "lon": -1.39, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "tottenham": {"stadio": "Tottenham Hotspur Stadium", "citta": "London", "campo": "erba_naturale", "lat": 51.60, "lon": -0.06, "media_cartellini": 2.3, "coperto": True}, #[cite: 1]
    "west ham": {"stadio": "London Stadium", "citta": "London", "campo": "erba_naturale", "lat": 51.53, "lon": -0.01, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "wolverhampton": {"stadio": "Molineux Stadium", "citta": "Wolverhampton", "campo": "erba_naturale", "lat": 52.59, "lon": -2.13, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]

    # SERIE B[cite: 1]
    "bari": {"stadio": "Stadio San Nicola", "citta": "Bari", "campo": "erba_naturale", "lat": 41.08, "lon": 16.82, "media_cartellini": 2.7, "coperto": False}, #[cite: 1]
    "brescia": {"stadio": "Stadio Mario Rigamonti", "citta": "Brescia", "campo": "erba_naturale", "lat": 45.56, "lon": 10.23, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "carrarese": {"stadio": "Stadio dei Marmi", "citta": "Carrara", "campo": "erba_naturale", "lat": 44.07, "lon": 10.08, "media_cartellini": 2.8, "coperto": False}, #[cite: 1]
    "cesena": {"stadio": "Orogel Stadium-Dino Manuzzi", "citta": "Cesena", "campo": "erba_naturale", "lat": 44.13, "lon": 12.24, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "cittadella": {"stadio": "Stadio Piercesare Tombolato", "citta": "Cittadella", "campo": "erba_naturale", "lat": 45.64, "lon": 11.78, "media_cartellini": 2.7, "coperto": False}, #[cite: 1]
    "cosenza": {"stadio": "Stadio San Vito-Gigi Marulla", "citta": "Cosenza", "campo": "erba_naturale", "lat": 39.31, "lon": 16.25, "media_cartellini": 2.8, "coperto": False}, #[cite: 1]
    "cremonese": {"stadio": "Stadio Giovanni Zini", "citta": "Cremona", "campo": "erba_naturale", "lat": 45.13, "lon": 10.03, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "juve stabia": {"stadio": "Stadio Romeo Menti", "citta": "Castellammare di Stabia", "campo": "erba_naturale", "lat": 40.70, "lon": 14.48, "media_cartellini": 2.7, "coperto": False}, #[cite: 1]
    "mantova": {"stadio": "Stadio Danilo Martelli", "citta": "Mantova", "campo": "erba_naturale", "lat": 45.16, "lon": 10.79, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "modena": {"stadio": "Stadio Alberto Braglia", "citta": "Modena", "campo": "erba_naturale", "lat": 44.65, "lon": 10.92, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "palermo": {"stadio": "Stadio Renzo Barbera", "citta": "Palermo", "campo": "erba_naturale", "lat": 38.15, "lon": 13.34, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "pisa": {"stadio": "Stadio Arena Garibaldi", "citta": "Pisa", "campo": "erba_naturale", "lat": 43.72, "lon": 10.40, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "reggiana": {"stadio": "Mapei Stadium", "citta": "Reggio Emilia", "campo": "erba_naturale", "lat": 44.71, "lon": 10.64, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "salernitana": {"stadio": "Stadio Arechi", "citta": "Salerno", "campo": "erba_naturale", "lat": 40.66, "lon": 14.82, "media_cartellini": 2.7, "coperto": False}, #[cite: 1]
    "sampdoria": {"stadio": "Stadio Luigi Ferraris", "citta": "Genova", "campo": "erba_naturale", "lat": 44.42, "lon": 8.95, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "sassuolo": {"stadio": "Mapei Stadium", "citta": "Reggio Emilia", "campo": "erba_naturale", "lat": 44.71, "lon": 10.64, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "spezia": {"stadio": "Stadio Alberto Picco", "citta": "La Spezia", "campo": "erba_naturale", "lat": 44.10, "lon": 9.82, "media_cartellini": 2.5, "coperto": False}, #[cite: 1]
    "sudtirol": {"stadio": "Stadio Druso", "citta": "Bolzano", "campo": "erba_naturale", "lat": 46.49, "lon": 11.34, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "catanzaro": {"stadio": "Stadio Nicola Ceravolo", "citta": "Catanzaro", "campo": "erba_naturale", "lat": 38.89, "lon": 16.59, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]

    # NAZIONALI[cite: 1]
    "italy": {"stadio": "Stadio Olimpico", "citta": "Roma", "campo": "erba_naturale", "lat": 41.93, "lon": 12.45, "media_cartellini": 2.2, "coperto": False}, #[cite: 1]
    "germany": {"stadio": "Olympiastadion", "citta": "Berlin", "campo": "erba_naturale", "lat": 52.51, "lon": 13.24, "media_cartellini": 1.8, "coperto": False}, #[cite: 1]
    "france": {"stadio": "Stade de France", "citta": "Saint-Denis", "campo": "erba_naturale", "lat": 48.92, "lon": 2.36, "media_cartellini": 1.9, "coperto": False}, #[cite: 1]
    "spain": {"stadio": "Santiago Bernabeu", "citta": "Madrid", "campo": "erba_ibrida", "lat": 40.45, "lon": -3.68, "media_cartellini": 1.7, "coperto": True}, #[cite: 1]
    "england": {"stadio": "Wembley Stadium", "citta": "London", "campo": "erba_naturale", "lat": 51.55, "lon": -0.27, "media_cartellini": 1.8, "coperto": True}, #[cite: 1]
    "brazil": {"stadio": "Maracana", "citta": "Rio de Janeiro", "campo": "erba_naturale", "lat": -22.91, "lon": -43.23, "media_cartellini": 2.6, "coperto": False}, #[cite: 1]
    "argentina": {"stadio": "Estadio Monumental", "citta": "Buenos Aires", "campo": "erba_naturale", "lat": -34.54, "lon": -58.45, "media_cartellini": 2.4, "coperto": False}, #[cite: 1]
    "portugal": {"stadio": "Estadio da Luz", "citta": "Lisbon", "campo": "erba_naturale", "lat": 38.75, "lon": -9.18, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "netherlands": {"stadio": "Johan Cruyff Arena", "citta": "Amsterdam", "campo": "erba_ibrida", "lat": 52.31, "lon": 4.94, "media_cartellini": 2.0, "coperto": True}, #[cite: 1]
    "belgium": {"stadio": "Stade Roi Baudouin", "citta": "Brussels", "campo": "erba_naturale", "lat": 50.89, "lon": 4.33, "media_cartellini": 2.1, "coperto": False}, #[cite: 1]
    "croatia": {"stadio": "Stadion Maksimir", "citta": "Zagreb", "campo": "erba_naturale", "lat": 45.81, "lon": 16.02, "media_cartellini": 2.3, "coperto": False}, #[cite: 1]
    "uruguay": {"stadio": "Estadio Centenario", "citta": "Montevideo", "campo": "erba_naturale", "lat": -34.89, "lon": -56.15, "media_cartellini": 2.8, "coperto": False} #[cite: 1]
}