# database_arbitri.py - Database unico unificato
# Indice di severità: 1 (permissivo) - 10 (severo)

DB_ARBITRI = {
    # SEVERISSIMI (Indice 9-10)
    "davide massa": 10,
    "gianluca aureliano": 10,
    "benjamin brand": 10,
    "frank willenborg": 10,
    "mateo busquets ferrer": 10,
    "willie delajod": 10,
    "paul tierney": 10,
    "fabio maresca": 9,
    "giuseppe collu": 9,
    "ivano pezzuto": 9,
    "davide di marco": 9,
    "florian exner": 9,
    "gil manzano": 9,
    "hernandez hernandez": 9,
    "cesar soto grado": 9,
    "jeremie pignard": 9,
    "bastien dechepy": 9,
    "simon hooper": 9,
    "darren england": 9,

    # SEVERI (Indice 7-8)
    "francesco fourneau": 8,
    "matteo marcenaro": 8,
    "michael fabbri": 8,
    "matteo gualtieri": 8,
    "paride tremolada": 8,
    "daniel siebert": 8,
    "matthias jöllenbeck": 8,
    "martinez munuera": 8,
    "alberola rojas": 8,
    "francois letexier": 8,
    "benoit bastien": 8,
    "michael oliver": 8,
    "anthony taylor": 8,
    "marco guida": 7,
    "maurizio mariani": 7,
    "giovanni ayroldi": 7,
    "alberto ruben arena": 7,
    "gianluca manganiello": 7,
    "simone galipò": 7,
    "tobias welz": 7,
    "daniel schlager": 7,
    "sanchez martinez": 7,
    "muniz ruiz": 7,
    "garcia verdura": 7,
    "ruddy buquet": 7,
    "jeremy stinat": 7,
    "eric wattellier": 7,
    "jarred gillett": 7,
    "david coote": 7,
    "craig pawson": 7,

    # MEDI (Indice 5-6)
    "federico la penna": 6,
    "rosario abisso": 6,
    "juan luca sacchi": 6,
    "andrea colombo": 6,
    "andrea zanotti": 6,
    "niccolò turrini": 6,
    "sören storks": 6,
    "patrick ittrich": 6,
    "munuera montero": 6,
    "cuadra fernandez": 6,
    "gomez ace": 6,
    "clement turpin": 6,
    "stéphanie frappart": 6,
    "florent batta": 6,
    "chris kavanagh": 6,
    "andy madley": 6,
    "tim robinson": 6,
    "giacomo camplone": 5,
    "matteo marchetti": 5,
    "simone sozza": 5,
    "daniele doveri": 5,
    "livio marinelli": 5,
    "felix zwayer": 5,
    "timo gerach": 5,
    "robin braun": 5,
    "de burgos bengoetxea": 5,
    "ortiz arias": 5,
    "maeso": 5,
    "mathieu vernice": 5,
    "gael angoula": 5,
    "robert jones": 5,
    "sam barrott": 5,

    # PERMISSIVI (Indice 1-4)
    "kevin bonacina": 4,
    "sven jablonski": 4,
    "florian badstübner": 4,
    "iglesias villanueva": 4,
    "figueroa vazquez": 4,
    "thomas leonard": 4,
    "benoit millot": 4,
    "john brooks": 4,
    "peter bankes": 4,
    "luca zufferli": 3,
    "daniele rutella": 3,
    "alessandro prontera": 3,
    "tobias stieler": 3,
    "sascha stegemann": 3,
    "harm osmers": 3,
    "pulido santana": 3,
    "garcia maeso": 3,
    "romain lissorgue": 3,
    "marc bollengier": 3,
    "tony harrington": 3,
    "michael salisbury": 3,
    "daniele perenzoni": 2,
    "ermanno feliciani": 2,
    "daniele chiffi": 2,
    "marco di bello": 2,
    "robert hartmann": 2,
    "deniz aytekin": 2,
    "ahmad heydari": 2,
    "stuart attwell": 2
}